### ISSUE TITLE
error after copy model files

### ISSUE THREAD

**Issue by lastessa** [cloud-annotations/object-detection-react#7]
<img width="1218" alt="image" src="https://user-images.githubusercontent.com/9418305/57838321-2a1c2780-77cd-11e9-948b-808b5e4a77f4.png">

**Comment by bourdakos1** [comment]
I’ve never seen this before

**Comment by bourdakos1** [comment]
I think the issue is that you are using a classification model instead of an object detection model. In the future I will build a version for classification+web, but I haven't gotten around to it yet. You can check out this blogpost which might be helpful in building it yourself https://hackernoon.com/start-using-tensorflow-js-without-leaving-this-article-fb683ac509ed
